spring.application.name=ai-service


# Server port
server.port=8080

groq.api.key=${GROQ_API_KEY}
#groq.model=llama-3.1-8b-instant
groq.model=meta-llama/llama-4-scout-17b-16e-instruct1
openrouter.api.key=${OPENROUTER_API_KEY}
#openrouter.model=openai/gpt-oss-120b
#openrouter.model=openai/gpt-oss-120b:free
openrouter.model=nvidia/nemotron-3-super-120b-a12b:free
#openrouter.model=qwen/qwen3-coder:free


internal.api.key=${aiservice}